[tool.poetry]
name = "tgtg"
version = "0.1.3"
description = "Unoffical python client for TooGoodToGo API"
readme = "README.md"
authors = ["Anthony Hivert <anthony.hivert@gmail.com>"]
repository = "https://github.com/ahivert/tgtg-python"

[tool.poetry.dependencies]
python = "^3.6"
requests = "2.23.0"


[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
black = "^19.3b0"
pytest = "^5.4.3"
responses = "^0.10.14"
pytest-cov = "^2.10.0"
isort = "^5.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
