[tool.poetry]
name = "tgtg"
version = "0.16.1"
description = "Unoffical python client for TooGoodToGo API"
readme = "README.md"
authors = ["Anthony Hivert <anthony.hivert@gmail.com>"]
repository = "https://github.com/ahivert/tgtg-python"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"

[tool.isort]
profile = "black"

[tool.poetry.dev-dependencies]
freezegun = "^1.2.2"
pre-commit = "^3.5.0"
pytest = "^7.4.2"
pytest-cov = "^4.1.0"
pytest-responses = "^0.5.1"
responses = "^0.23.3"
typed-ast = "^1.5.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
